name: Dev/Main Pipeline # call it how you feel like

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs: #more efficient jobs.  
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm run test

  trigger_security_pipeline: #Wee security
    needs: build
    runs-on: ubuntu-latest

    steps: #Here are the steps. idk. i had to fix it multiple times by now. 
      - name: Trigger Security Pipeline
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context, github } = require('@actions/github');
            const { owner, repo } = context.repo;
            const pullRequestNumber = context.payload.number || context.payload.pull_request?.number;
            github.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: 'security-pipeline.yml',
              ref: context.ref,
              inputs: {
                pull_request_number: pullRequestNumber
              }
            })

      - name: Add or Update Comment #commenting or updating a comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            The code has passed all necessary checks.
