name: Dev/Main Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs: #more efficient jobs 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm run test

  trigger_security_pipeline: #yeah, security. neat.
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Security Pipeline
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context, github } = require('@actions/github');
            const { owner, repo } = context.repo;
            github.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: 'security-pipeline.yml'
            })

      - name: Add or Update Comment #Comment adding, nothing much to it.
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            The code has passed all necessary checks.
