name: Security Pipeline #This entire thing might be wrong, who knows. 

on:
  workflow_dispatch: {}

jobs:
  security_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Security Scanning
        uses: github/codeql-action/analyze@v2
        with:
          languages: javascript, typescript

      - name: Static Code Analysis
        uses: codeclimate/codeclimate-action@v3
        with:
          enable_fixes: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*
          tag_name: ${{ github.sha }}
          body: Release ${{ github.sha }}

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./path/to/artifact

# removed the commenting on the security, idk, felt like its not needed if its required on the main. 
# added type script in the scanning. 